### ISSUE TITLE
Application declined but still visible in general search

### ISSUE THREAD

**Issue by elixawu** [calblueprint/nbjc#93]
**Describe the bug**
Title. Application "hitiffany" was declined but then on the main search page when you click search with no names or filters, you see all orgs, and draft, rejected ones are all visible.

**To Reproduce**
1. Make org
2. Reject
3. Search on the main page
4. See the rejected org listed

**Expected behavior**
Should not display the rejected org on blank search

**Screenshots**
![Screen Shot 2021-04-17 at 5 41 26 PM](https://user-images.githubusercontent.com/8762183/115130368-24748100-9fa4-11eb-80cb-3bc7ae2dea2a.png)

**Comment by claalmve** [comment]
Similar to #82.
